// <auto-generated />
using System;
using B1ngo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace B1ngo.Infrastructure.Migrations
{
    [DbContext(typeof(B1ngoDbContext))]
    [Migration("20260320203347_ReshapeReferenceDataForJolpica")]
    partial class ReshapeReferenceDataForJolpica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B1ngo.Domain.Game.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<bool>("HasWon")
                        .HasColumnType("boolean")
                        .HasColumnName("has_won");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("B1ngo.Domain.Game.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_player_id");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("join_code");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("B1ngo.Infrastructure.Auth.PlayerToken", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsHost")
                        .HasColumnType("boolean")
                        .HasColumnName("is_host");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Token");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_tokens_player_id");

                    b.ToTable("player_tokens", (string)null);
                });

            modelBuilder.Entity("B1ngo.Infrastructure.ReferenceData.EventPoolEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("display_text");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_key");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session_type");

                    b.HasKey("Id");

                    b.HasIndex("SessionType", "EventKey")
                        .IsUnique();

                    b.ToTable("event_pool_entries", (string)null);
                });

            modelBuilder.Entity("B1ngo.Infrastructure.ReferenceData.GrandPrixEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSprint")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sprint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.PrimitiveCollection<string>("SessionTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("session_types");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Season")
                        .IsUnique();

                    b.ToTable("grand_prix", (string)null);
                });

            modelBuilder.Entity("B1ngo.Domain.Game.Player", b =>
                {
                    b.HasOne("B1ngo.Domain.Game.Room", null)
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("B1ngo.Domain.Game.BingoCard", "Card", b1 =>
                        {
                            b1.Property<Guid>("PlayerId");

                            b1.Property<int>("MatrixSize");

                            b1.HasKey("PlayerId");

                            b1.ToTable("players");

                            b1
                                .ToJson("Card")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");

                            b1.OwnsMany("B1ngo.Domain.Game.BingoSquare", "Squares", b2 =>
                                {
                                    b2.Property<Guid>("BingoCardPlayerId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Column");

                                    b2.Property<string>("DisplayText")
                                        .IsRequired();

                                    b2.Property<string>("EventKey");

                                    b2.Property<bool>("IsFreeSpace");

                                    b2.Property<bool>("IsMarked");

                                    b2.Property<DateTimeOffset?>("MarkedAt");

                                    b2.Property<int?>("MarkedBy");

                                    b2.Property<int>("Row");

                                    b2.HasKey("BingoCardPlayerId", "__synthesizedOrdinal");

                                    b2.ToTable("players");

                                    b2.WithOwner()
                                        .HasForeignKey("BingoCardPlayerId");
                                });

                            b1.Navigation("Squares");
                        });

                    b.Navigation("Card");
                });

            modelBuilder.Entity("B1ngo.Domain.Game.Room", b =>
                {
                    b.OwnsOne("B1ngo.Domain.Game.RaceSession", "Session", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("GrandPrixName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("grand_prix_name");

                            b1.Property<int>("Season")
                                .HasColumnType("integer")
                                .HasColumnName("season");

                            b1.Property<string>("SessionType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("session_type");

                            b1.HasKey("Id");

                            b1.ToTable("rooms");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsMany("B1ngo.Domain.Game.LeaderboardEntry", "Leaderboard", b1 =>
                        {
                            b1.Property<Guid>("RoomId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTimeOffset>("CompletedAt");

                            b1.Property<Guid>("PlayerId");

                            b1.Property<int>("Rank");

                            b1.Property<string>("WinningPattern")
                                .IsRequired();

                            b1.HasKey("RoomId", "__synthesizedOrdinal");

                            b1.ToTable("rooms");

                            b1
                                .ToJson("Leaderboard")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");

                            b1.OwnsMany("B1ngo.Domain.Game.SquarePosition", "WinningSquares", b2 =>
                                {
                                    b2.Property<Guid>("LeaderboardEntryRoomId");

                                    b2.Property<int>("LeaderboardEntry__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Column");

                                    b2.Property<int>("Row");

                                    b2.HasKey("LeaderboardEntryRoomId", "LeaderboardEntry__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("rooms");

                                    b2.WithOwner()
                                        .HasForeignKey("LeaderboardEntryRoomId", "LeaderboardEntry__synthesizedOrdinal");
                                });

                            b1.Navigation("WinningSquares");
                        });

                    b.OwnsOne("B1ngo.Domain.Game.RoomConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("RoomId");

                            b1.Property<int>("MatrixSize");

                            b1.Property<int>("MaxPlayers");

                            b1.PrimitiveCollection<string>("WinningPatterns")
                                .IsRequired();

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1
                                .ToJson("Configuration")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("Leaderboard");

                    b.Navigation("Session")
                        .IsRequired();
                });

            modelBuilder.Entity("B1ngo.Domain.Game.Room", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
