// <auto-generated />
using System;
using B1ngo.Infrastructure;
using B1ngo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace B1ngo.Infrastructure.Migrations
{
    [DbContext(typeof(B1ngoDbContext))]
    [Migration("20260313130118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B1ngo.Domain.Game.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("B1ngo.Domain.Game.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("join_code");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.HasKey("Id");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("B1ngo.Domain.Game.Player", b =>
                {
                    b.HasOne("B1ngo.Domain.Game.Room", null)
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("B1ngo.Domain.Game.BingoCard", "BingoCard", b1 =>
                        {
                            b1.Property<Guid>("PlayerId");

                            b1.HasKey("PlayerId");

                            b1.ToTable("players");

                            b1
                                .ToJson("BingoCard")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");

                            b1.OwnsMany("B1ngo.Domain.Game.BingoSquare", "Squares", b2 =>
                                {
                                    b2.Property<Guid>("BingoCardPlayerId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Col");

                                    b2.Property<string>("DisplayText")
                                        .IsRequired();

                                    b2.Property<int>("Row");

                                    b2.HasKey("BingoCardPlayerId", "__synthesizedOrdinal");

                                    b2.ToTable("players");

                                    b2.WithOwner()
                                        .HasForeignKey("BingoCardPlayerId");
                                });

                            b1.Navigation("Squares");
                        });

                    b.Navigation("BingoCard");
                });

            modelBuilder.Entity("B1ngo.Domain.Game.Room", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
