using B1ngo.Domain.Game;

namespace B1ngo.Infrastructure.CardGeneration;

internal static class EventPool
{
    public static IReadOnlyList<EventPoolEntry> GetEvents(SessionType sessionType)
        => sessionType switch
        {
            SessionType.Race => RaceEvents,
            SessionType.Qualifying => QualifyingEvents,
            SessionType.Sprint => SprintEvents,
            SessionType.SprintQualifying => SprintQualifyingEvents,
            SessionType.FP1 or SessionType.FP2 or SessionType.FP3 => PracticeEvents,
            _ => RaceEvents
        };

    private static readonly List<EventPoolEntry> RaceEvents =
    [
        new("SAFETY_CAR", "Safety Car"),
        new("VIRTUAL_SAFETY_CAR", "Virtual Safety Car"),
        new("RED_FLAG", "Red Flag"),
        new("FASTEST_LAP", "Fastest Lap"),
        new("DRIVER_OF_THE_DAY", "Driver of the Day"),
        new("PODIUM_FINISH", "Podium Finish"),
        new("PIT_STOP_UNDER_3S", "Pit Stop Under 3s"),
        new("DOUBLE_STACK", "Double Stack Pit Stop"),
        new("OVERTAKE_FOR_LEAD", "Overtake for the Lead"),
        new("DRS_OVERTAKE", "DRS Overtake"),
        new("TEAM_RADIO_RAGE", "Angry Team Radio"),
        new("PENALTY_ISSUED", "Penalty Issued"),
        new("TRACK_LIMITS_WARNING", "Track Limits Warning"),
        new("TYRE_BLOWOUT", "Tyre Blowout"),
        new("RAIN_STARTS", "Rain Starts"),
        new("FORMATION_LAP_DRAMA", "Formation Lap Drama"),
        new("FIRST_LAP_INCIDENT", "First Lap Incident"),
        new("RETIREMENT", "Retirement"),
        new("BLUE_FLAGS_SHOWN", "Blue Flags Shown"),
        new("ENGINE_FAILURE", "Engine Failure"),
        new("COLLISION", "Collision"),
        new("UNDERCUT_ATTEMPT", "Undercut Attempt"),
        new("OVERCUT_ATTEMPT", "Overcut Attempt"),
        new("WRONG_TYRE_FITTED", "Wrong Tyre Fitted"),
        new("SLOW_PIT_STOP", "Slow Pit Stop (5s+)"),
        new("CHEQUERED_FLAG", "Chequered Flag"),
        new("LOCK_UP", "Lock Up"),
        new("GRAVEL_EXCURSION", "Gravel Excursion"),
        new("CHAMPIONSHIP_LEADER_CHANGE", "Championship Leader Changes"),
        new("TEAM_ORDERS", "Team Orders Issued"),
        new("STRATEGY_GAMBLE", "Strategy Gamble"),
        new("DEBRIS_ON_TRACK", "Debris on Track"),
        new("MEDICAL_CAR_DEPLOYED", "Medical Car Deployed"),
        new("PHOTO_FINISH", "Photo Finish"),
        new("LAPPED_CAR_UNLAPS", "Lapped Car Unlaps Itself"),
    ];

    private static readonly List<EventPoolEntry> QualifyingEvents =
    [
        new("POLE_POSITION", "Pole Position"),
        new("RED_FLAG_Q", "Red Flag in Qualifying"),
        new("TRACK_EVOLUTION", "Track Evolution Matters"),
        new("Q1_KNOCKOUT", "Surprise Q1 Knockout"),
        new("Q2_KNOCKOUT", "Surprise Q2 Knockout"),
        new("TRAFFIC_DRAMA", "Traffic Drama"),
        new("PURPLE_SECTOR", "Purple Sector"),
        new("BANKER_LAP", "Banker Lap Mentioned"),
        new("FINAL_FLYING_LAP", "Final Flying Lap Drama"),
        new("FRONT_ROW_LOCKOUT", "Front Row Lockout"),
        new("LAP_DELETED", "Lap Deleted (Track Limits)"),
        new("MECHANICAL_ISSUE", "Mechanical Issue"),
        new("CRASH_IN_QUALIFYING", "Crash in Qualifying"),
        new("YELLOW_FLAG_DISRUPTION", "Yellow Flag Disruption"),
        new("SLIPSTREAM_TOW", "Slipstream/Tow Used"),
        new("TYRE_STRATEGY_SPLIT", "Tyre Strategy Split"),
        new("TEAM_RADIO_FRUSTRATION", "Frustration on Team Radio"),
        new("NEW_TRACK_RECORD", "New Track Record"),
        new("GEAR_BOX_ISSUE", "Gearbox Issue"),
        new("POWER_UNIT_CHANGE", "Power Unit Change"),
        new("GRID_PENALTY_APPLIED", "Grid Penalty Applied"),
        new("WEATHER_CHANGE", "Weather Change"),
        new("SESSION_DELAYED", "Session Delayed"),
        new("DRIVER_GOES_OFF", "Driver Goes Off Track"),
        new("SANDBAGGING_ACCUSATION", "Sandbagging Mentioned"),
        new("SPLIT_TIMES_TIGHT", "Split Times Within 0.1s"),
        new("OUTLAP_ISSUES", "Outlap Issues"),
        new("COOL_DOWN_LAP", "Cool-Down Lap Shown"),
        new("SETUP_CHANGE", "Setup Change Mentioned"),
        new("WING_ADJUSTMENT", "Wing Adjustment Shown"),
        new("DRS_DETECTION_ISSUE", "DRS Detection Issue"),
    ];

    private static readonly List<EventPoolEntry> SprintEvents =
    [
        new("SPRINT_SAFETY_CAR", "Safety Car in Sprint"),
        new("SPRINT_FASTEST_LAP", "Sprint Fastest Lap"),
        new("SPRINT_OVERTAKE_LEAD", "Overtake for Sprint Lead"),
        new("SPRINT_DRS_PASS", "DRS Overtake in Sprint"),
        new("SPRINT_CONTACT", "Contact in Sprint"),
        new("SPRINT_RETIREMENT", "Retirement in Sprint"),
        new("SPRINT_PENALTY", "Penalty in Sprint"),
        new("SPRINT_FIRST_LAP", "First Lap Incident"),
        new("SPRINT_TEAM_RADIO", "Team Radio in Sprint"),
        new("SPRINT_STRATEGY", "Strategy Surprise in Sprint"),
        new("SPRINT_TRACK_LIMITS", "Track Limits in Sprint"),
        new("SPRINT_LOCK_UP", "Lock Up in Sprint"),
        new("SPRINT_POSITION_SWAP", "Position Swap in Sprint"),
        new("SPRINT_DEBRIS", "Debris in Sprint"),
        new("SPRINT_BLUE_FLAGS", "Blue Flags in Sprint"),
        new("SPRINT_VSC", "Virtual Safety Car in Sprint"),
        new("SPRINT_RED_FLAG", "Red Flag in Sprint"),
        new("SPRINT_TYRE_DEG", "Tyre Degradation Issues"),
        new("SPRINT_PHOTO_FINISH", "Close Finish in Sprint"),
        new("SPRINT_POINTS_CHANGE", "Championship Points Change"),
        new("SPRINT_GRAVEL", "Gravel Excursion in Sprint"),
        new("SPRINT_COLLISION", "Collision in Sprint"),
        new("SPRINT_ENGINE_ISSUE", "Engine Issue in Sprint"),
        new("SPRINT_TEAM_ORDERS", "Team Orders in Sprint"),
        new("SPRINT_UNDERCUT", "Undercut in Sprint"),
        new("SPRINT_FORMATION", "Formation Lap Issue"),
        new("SPRINT_RAIN", "Rain in Sprint"),
        new("SPRINT_WING_DAMAGE", "Wing Damage in Sprint"),
        new("SPRINT_PIT_ERROR", "Pit Stop Error in Sprint"),
        new("SPRINT_DOUBLE_STACK", "Double Stack in Sprint"),
        new("SPRINT_CHECKERED", "Sprint Finish"),
    ];

    private static readonly List<EventPoolEntry> SprintQualifyingEvents =
    [
        new("SQ_POLE", "Sprint Qualifying Pole"),
        new("SQ_RED_FLAG", "Red Flag in Sprint Qualifying"),
        new("SQ_SURPRISE_KNOCKOUT", "Surprise Knockout"),
        new("SQ_TRAFFIC", "Traffic in Sprint Qualifying"),
        new("SQ_PURPLE_SECTOR", "Purple Sector"),
        new("SQ_LAP_DELETED", "Lap Deleted"),
        new("SQ_CRASH", "Crash in Sprint Qualifying"),
        new("SQ_YELLOW_FLAG", "Yellow Flag"),
        new("SQ_SLIPSTREAM", "Slipstream Used"),
        new("SQ_TEAM_RADIO", "Team Radio Drama"),
        new("SQ_TRACK_RECORD", "Track Record Broken"),
        new("SQ_WEATHER", "Weather Change"),
        new("SQ_MECHANICAL", "Mechanical Issue"),
        new("SQ_GRID_PENALTY", "Grid Penalty"),
        new("SQ_TIGHT_MARGINS", "Margins Within 0.1s"),
        new("SQ_OUTLAP_ISSUE", "Outlap Issue"),
        new("SQ_FRONT_ROW", "Front Row Lockout"),
        new("SQ_STRATEGY_SPLIT", "Strategy Split"),
        new("SQ_DRIVER_ERROR", "Driver Error"),
        new("SQ_SESSION_DELAY", "Session Delayed"),
        new("SQ_SANDBAGGING", "Sandbagging Mentioned"),
        new("SQ_WING_CHANGE", "Wing Change"),
        new("SQ_SETUP_ISSUE", "Setup Issue"),
        new("SQ_BANKER_LAP", "Banker Lap"),
        new("SQ_FINAL_ATTEMPT", "Final Attempt Drama"),
        new("SQ_DRS_ISSUE", "DRS Issue"),
        new("SQ_GEAR_PROBLEM", "Gear Problem"),
        new("SQ_TRACK_EVOLUTION", "Track Evolution"),
        new("SQ_LOCKUP", "Lock Up"),
        new("SQ_OFF_TRACK", "Goes Off Track"),
        new("SQ_FRUSTRATION", "Driver Frustration"),
    ];

    private static readonly List<EventPoolEntry> PracticeEvents =
    [
        new("FP_RED_FLAG", "Red Flag in Practice"),
        new("FP_FASTEST_TIME", "Fastest Time Set"),
        new("FP_LONG_RUN", "Long Run Pace Analysis"),
        new("FP_SHORT_RUN", "Short Run Mentioned"),
        new("FP_TYRE_TEST", "Tyre Compound Test"),
        new("FP_AERO_RAKE", "Aero Rake Spotted"),
        new("FP_SPIN", "Spin in Practice"),
        new("FP_CRASH", "Crash in Practice"),
        new("FP_GEARBOX_ISSUE", "Gearbox Issue"),
        new("FP_ENGINE_PROBLEM", "Engine Problem"),
        new("FP_TRACK_LIMITS", "Track Limits Warning"),
        new("FP_TEAM_RADIO", "Team Radio in Practice"),
        new("FP_SETUP_CHANGE", "Setup Change"),
        new("FP_TRAFFIC", "Traffic in Practice"),
        new("FP_WEATHER_CHANGE", "Weather Change"),
        new("FP_SESSION_DELAYED", "Session Delayed"),
        new("FP_GRAVEL", "Gravel Excursion"),
        new("FP_DEBRIS", "Debris on Track"),
        new("FP_YELLOW_FLAG", "Yellow Flag"),
        new("FP_DRS_TEST", "DRS Test"),
        new("FP_RESERVE_DRIVER", "Reserve Driver Appearance"),
        new("FP_NEW_PARTS", "New Parts Tested"),
        new("FP_BRAKE_ISSUE", "Brake Issue"),
        new("FP_HYDRAULIC_LEAK", "Hydraulic Leak"),
        new("FP_FLOOR_DAMAGE", "Floor Damage"),
        new("FP_WING_ADJUSTMENT", "Wing Adjustment"),
        new("FP_COOLING_ISSUE", "Cooling Issue"),
        new("FP_LOCK_UP", "Lock Up"),
        new("FP_COMPARISON_SHOWN", "Comparison Data Shown"),
        new("FP_SECTOR_ANALYSIS", "Sector Analysis"),
        new("FP_PIT_PRACTICE", "Pit Stop Practice"),
    ];
}

public sealed record EventPoolEntry(string EventKey, string DisplayText);
